#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed "s/ENABLED=0/ENABLED=1" /etc/default/haproxy
$new_config="
    frontend http_front
        bind *:80
        default_backend http-backend
    backend http-backend
        balance roundrobin
        server 76213-web-01 54.242.169.136:80 check
        server 76213-web-02 54.146.90.12:80 check
"
sudo echo new_config >> /etc/haproxy/haproxy.cfg
service haproxy start
